import { readFileSync, writeFileSync } from 'node:fs'

const inventory = JSON.parse(readFileSync('coverage/nodes-5.2.2.json', 'utf8'))
const status = JSON.parse(readFileSync('coverage/status.json', 'utf8'))
const FAMILY_ORDER = ['Geometry', 'Function', 'Shader', 'Node']

function familyOf(idname) {
  return idname.match(/^[A-Z][a-z]+/)[0]
}

function stateOf(idname) {
  const entry = status[idname]
  if (!entry) return 'pending'
  return entry.verified ? 'verified' : entry.ported ? 'ported' : 'pending'
}

const counts = { pending: 0, ported: 0, verified: 0 }
for (const node of inventory.nodes) counts[stateOf(node.idname)] += 1

const sections = FAMILY_ORDER.map((family) => {
  const rows = inventory.nodes
    .filter((node) => familyOf(node.idname) === family)
    .map((node) => `| \`${node.idname}\` | ${node.label} | ${stateOf(node.idname)} |`)
  return `## ${family} (${rows.length})\n\n| Node | Label | State |\n|---|---|---|\n${rows.join('\n')}`
})

const header = `# Node coverage — Blender ${inventory.blender} (${inventory.hash})

Generated by \`node tools/coverage.mjs\` from \`coverage/nodes-5.2.2.json\` and \`coverage/status.json\`. Do not edit by hand.

| State | Nodes |
|---|---|
| verified | ${counts.verified} |
| ported | ${counts.ported} |
| pending | ${counts.pending} |
| **total** | **${inventory.nodes.length}** |
`
writeFileSync('docs/coverage.md', `${header}\n${sections.join('\n\n')}\n`)
console.log(`coverage: ${counts.verified} verified, ${counts.ported} ported, ${counts.pending} pending of ${inventory.nodes.length}`)
